### ISSUE TITLE
fastify-auth does not work with async strategies

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/fastify-auth#35]
Hello,

I don't know if this is a bug or feature, but it seems that `fastify-auth` does not currently support async authentication strategies:
https://github.com/PP-etc/fastify-auth-with-async-pre-handler/blob/master/__tests__/stucks.test.js#L8

Declaration above will never be resolved, since `done` is not passed and not called.

While originally `preHandler` (and it's father `beforeHandler`) do support `async`:
https://www.fastify.io/docs/latest/Hooks/#respond-to-a-request-from-a-hook

Should this be fixed?

**Comment by Eomm** [comment]
You are right:

https://github.com/fastify/fastify-auth/blob/ff39b870b056170a378294b3114eed63446d3ee0/fastify-auth.js#L62
We accept only functions as input and not `Promise`.

Would you like to work on a PR to add this feature?

**Comment by PavelPolyakov** [comment]
Sure, let's see what I can do. I believe such mechanism is already present in `fastify`, if you know on top of your head where to find it - please share. Otherwise I'll find it during next week work days.

**Comment by Eomm** [comment]
I don't think it is a matter of `preHandler` or hooks because the target is the input array functions.

This plugin returns a function that could be attached to any hooks in fastify:

https://github.com/fastify/fastify-auth/blob/ff39b870b056170a378294b3114eed63446d3ee0/fastify-auth.js#L25

But the problem is how this array is managed:

https://github.com/fastify/fastify-auth/blob/ff39b870b056170a378294b3114eed63446d3ee0/fastify-auth.js#L31

So I think you need to find if the array element is a function or promise and then if it is a function nothing change, but if it is a promise you need to wait for it an then call the `that.onAuth` to continue the workflow.

https://github.com/fastify/fastify-auth/blob/ff39b870b056170a378294b3114eed63446d3ee0/fastify-auth.js#L62

**Comment by mcollina** [comment]
Typings is an afterfact. This library is not written in typescript, and the JS is the source of truth.

The API should either be:

``` js
.decorate('verifyJWTandLevel', async function (request, reply) {
    // your async stuff
  })
```

or

```js
.decorate('verifyJWTandLevel', function (request, reply, done) {
    // your validation logic
    done() // pass an error if the authentication fails
  })
```

The typescript definition should be updated.

**Comment by SkeLLLa** [comment]
@mcollina The JS source of truth is good, but I think it will be better if that truth come to readme as well :)
