### ISSUE TITLE
What about Basic Auth?

### ISSUE THREAD

**Issue by activestylus** [fastify/fastify-auth#7]
In hapi you can do this. Pretty straight forward.

Any idea how to do this with fastify?

```
await server.register(require('hapi-auth-basic'));

    server.auth.strategy('simple', 'basic', { validate });
    server.auth.default('simple');

    server.route({
        method: 'GET',
        path: '/',
        handler: function (request, h) {

            return 'welcome';
        }
    });

    await server.start();
```

**Comment by shinzui** [comment]
It's surprising that fastify does not support basic auth. I was going to use it to quickly set up a webhook endpoint for a service that only supports basic auth, but I'll stick with Hapi for now.

**Comment by mcollina** [comment]
Hapi is a great framework, keep using it!

**Comment by delvedor** [comment]
No surprises at all. Fastify aims to be as light as possible. We decided to not offer anything out of the box because every project has its needs- especially when talking about authorization.

Take the basic auth, for instance, get the authorization header is super easy, the most "complex" part is where you validate that data, which databases are you using, which crypto library and so on. There is no plugin which will do this for you, even for Hapi where you must give a validate function which is doing most of the work.

You just to define an `onRequest` hook, use [basic-auth](https://github.com/jshttp/basic-auth) to parse the header and write your authentication logic.
